# Generated by Django 5.1.4 on 2025-01-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_team_task_teammembership_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
