# Generated by Django 5.1.4 on 2025-01-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0005_task_team_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
