# Generated by Django 5.1.4 on 2025-03-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0008_rename_name_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(),
        ),
    ]
