# Generated by Django 5.1.4 on 2025-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0009_alter_document_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
