# Generated by Django 5.1.4 on 2025-03-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0010_document_google_drive_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='review_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
